const data = {
  products: [
    {
      name: 'Cotton Crewneck T-Shirt',
      category: 'T-Shirt',
      image: '/images/p1.jpg',
      price: 25,
      countInStock: 50,
      brand: 'XYZ Clothing',
      rating: 4.5,
      numReviews: 18,
      description: 'Soft and comfortable cotton crewneck t-shirt.',
    },
    {
      name: 'Classic Canvas Sneakers',
      category: 'Sneakers',
      image: '/images/p2.jpg',
      price: 60,
      countInStock: 30,
      brand: 'FootFlex',
      rating: 4.2,
      numReviews: 12,
      description: 'Timeless canvas sneakers with durable rubber soles.',
    },
    {
      name: 'Elegant Evening Dress',
      category: 'Dress',
      image: '/images/p3.jpg',
      price: 120,
      countInStock: 15,
      brand: 'GlamourBoutique',
      rating: 4.8,
      numReviews: 30,
      description: 'A stunning evening dress perfect for special occasions.',
    },
    {
      name: 'Floral Print Summer Dress',
      category: 'Dress',
      image: '/images/p4.jpg',
      price: 45,
      countInStock: 30,
      brand: 'ChicStyles',
      rating: 4.7,
      numReviews: 25,
      description: 'A stylish floral print dress for the summer season.',
    },
    {
      name: 'Outdoor Adventure Backpack',
      category: 'Backpack',
      image: '/images/p5.jpg',
      price: 75,
      countInStock: 25,
      brand: 'AdventureGear',
      rating: 4.7,
      numReviews: 21,
      description: 'Spacious and durable backpack for outdoor enthusiasts.',
    },
    {
      name: 'Luxury Chronograph Watch',
      category: 'Watch',
      image: '/images/p6.jpg',
      price: 199,
      countInStock: 10,
      brand: 'TimeMaster',
      rating: 4.9,
      numReviews: 38,
      description: 'A stylish chronograph watch with stainless steel band.',
    },
    {
      name: 'Elegant Gold-Plated Watch',
      category: 'Watch',
      image: '/images/p7.jpg',
      price: 150,
      countInStock: 15,
      brand: 'TimeLux',
      rating: 4.8,
      numReviews: 22,
      description: 'An elegant gold-plated watch with a leather strap.',
    },
    {
      name: 'Slim Fit Denim Jeans',
      category: 'Jeans',
      image: '/images/p8.jpg',
      price: 55,
      countInStock: 25,
      brand: 'DenimCo',
      rating: 4.4,
      numReviews: 17,
      description: 'Stylish slim fit denim jeans with a classic design.',
    },
    {
      name: 'Designer Leather Handbag',
      category: 'Handbag',
      image: '/images/p9.jpg',
      price: 120,
      countInStock: 20,
      brand: 'LuxuryBags',
      rating: 4.9,
      numReviews: 30,
      description: 'Luxurious leather handbag with a designer touch.',
    },
    {
      name: 'Flagship Smartphone',
      category: 'Smartphone',
      image: '/images/p10.jpg',
      price: 699,
      countInStock: 10,
      brand: 'TechMaster',
      rating: 4.9,
      numReviews: 50,
      description: 'High-end smartphone with top-of-the-line features.',
    },
    {
      name: 'Wireless Over-Ear Headphones',
      category: 'Headphones',
      image: '/images/p11.jpg',
      price: 89,
      countInStock: 30,
      brand: 'SoundWave',
      rating: 4.7,
      numReviews: 40,
      description: 'Premium wireless headphones for immersive audio.',
    },
    {
      name: 'Adjustable Dumbbell Set',
      category: 'Fitness Equipment',
      image: '/images/p12.jpg',
      price: 149,
      countInStock: 15,
      brand: 'FitLife',
      rating: 4.5,
      numReviews: 35,
      description: 'Versatile dumbbell set for home workouts.',
    },
    {
      name: 'Slim Ultrabook Laptop',
      category: 'Laptop',
      image: '/images/p13.jpg',
      price: 899,
      countInStock: 12,
      brand: 'TechGenius',
      rating: 4.7,
      numReviews: 42,
      description: 'Sleek and powerful ultrabook laptop for productivity.',
    },
    {
      name: 'Compact Travel Umbrella',
      category: 'Umbrella',
      image: '/images/p14.jpg',
      price: 19,
      countInStock: 40,
      brand: 'RainShield',
      rating: 4.4,
      numReviews: 16,
      description:
        'Compact and durable umbrella for on-the-go rain protection.',
    },
    {
      name: 'Gaming Console Bundle',
      category: 'Gaming Console',
      image: '/images/p15.jpg',
      price: 399,
      countInStock: 8,
      brand: 'GameMaster',
      rating: 4.8,
      numReviews: 25,
      description: 'Gaming console bundle with popular games included.',
    },
    {
      name: 'Mirrorless Digital Camera',
      category: 'Digital Camera',
      image: '/images/p16.jpg',
      price: 599,
      countInStock: 10,
      brand: 'PhotoPro',
      rating: 4.8,
      numReviews: 36,
      description:
        'High-resolution mirrorless digital camera for photography enthusiasts.',
    },
    {
      name: 'Eau de Parfum Spray',
      category: 'Perfume',
      image: '/images/p17.jpg',
      price: 55,
      countInStock: 15,
      brand: 'FragranceFusion',
      rating: 4.6,
      numReviews: 30,
      description:
        'A captivating Eau de Parfum spray with a long-lasting fragrance.',
    },
  ],
};

export default data;
